# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projektit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registereduser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('auth_token', models.CharField(max_length=100, null=True)),
                ('token_valid_until', models.DateTimeField(null=True)),
                ('avatar', models.CharField(default='default.jpg', max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
