# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0006_auto_20171111_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='avatar',
        ),
        migrations.AddField(
            model_name='activationproject',
            name='cover_photo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activationproject',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='activationproject',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projektit.Registereduser'),
        ),
        migrations.AlterField(
            model_name='activationproject',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='avatar_base64',
            field=models.CharField(max_length=300000, null=True),
        ),
    ]
