# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0007_auto_20171114_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationproject',
            name='url_token',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
