# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0008_activationproject_url_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='url_token',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
