# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0009_registereduser_url_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('proof1', models.CharField(max_length=100, null=True)),
                ('proof2', models.CharField(max_length=100, null=True)),
                ('step_taken', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='activationproject',
            name='latest_step_taken',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='activationproject',
            name='project_started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektit.Activationproject'),
        ),
    ]
