# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0010_auto_20171116_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='avatar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
