# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0013_auto_20171202_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationproject',
            name='numeric_goal_unit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activationproject',
            name='step_ratings',
            field=models.BooleanField(default=False),
        ),
    ]
