# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0016_auto_20171205_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activationproject',
            name='latest_step_taken',
        ),
    ]
