# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-23 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0017_remove_activationproject_latest_step_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektit.Activationproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektit.Registereduser')),
            ],
        ),
    ]
