# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-23 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0018_projectlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationproject',
            name='like_count',
            field=models.IntegerField(null=True),
        ),
    ]
