# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0019_activationproject_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StepLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='step',
            name='like_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activationproject',
            name='like_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='steplike',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektit.Step'),
        ),
        migrations.AddField(
            model_name='steplike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektit.Registereduser'),
        ),
        migrations.AddField(
            model_name='projectfollow',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektit.Activationproject'),
        ),
        migrations.AddField(
            model_name='projectfollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektit.Registereduser'),
        ),
    ]
