# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0020_auto_20171230_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationproject',
            name='project_likes_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activationproject',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='activationproject',
            name='step_likes_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
