# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0022_auto_20180115_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationproject',
            name='certificated_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activationproject',
            name='certificated_root_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projektit.Activationproject'),
        ),
    ]
