# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-27 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0025_auto_20180125_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='password_reset_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='password_reset_token_valid_until',
            field=models.DateTimeField(null=True),
        ),
    ]
