# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0029_auto_20180128_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='activationproject',
            name='step_comments_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projektit.Activationproject'),
        ),
        migrations.AddField(
            model_name='comment',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projektit.Step'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektit.Registereduser'),
        ),
    ]
