# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-27 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0031_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='proof_s3_key',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='proof_s3_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
