# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-24 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0032_auto_20180327_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationproject',
            name='cover_photo_s3_key',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activationproject',
            name='cover_photo_s3_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
