# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-09 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0038_auto_20190522_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationproject',
            name='challenge_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activationproject',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
