# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-22 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0041_jwtauthenticationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jwtauthenticationtoken',
            name='logged_in',
        ),
        migrations.AlterField(
            model_name='jwtauthenticationtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektit.Registereduser'),
        ),
    ]
