# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-01 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0043_auto_20190801_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlike',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectlike',
            name='user',
        ),
        migrations.AddField(
            model_name='steplike',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_likes', to='projektit.Project'),
        ),
        migrations.AlterField(
            model_name='steplike',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_likes', to='projektit.Step'),
        ),
        migrations.DeleteModel(
            name='ProjectLike',
        ),
    ]
