# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-01 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektit', '0044_auto_20190801_2102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StepLike',
            new_name='Like',
        ),
    ]
